name: iRedScarf
title: iRedScarf
description: A Red Scarf Shared Something Here
show_downloads: false
intensedebate_comments: true
jekyll-feed: true
baseurl: 
url: "https://iRedScarf.github.io"

google_analytics:
# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
author: "iRedScarf"
image: /iRedScarf.png
twitter:
  username: 
#  site:
facebook:
  #publisher: 
  #profile_id: 
  app_id: # cayman-blog
  #authors: 
#  admins:
