title: A Red Scarf Shared Something Here
description: 
show_downloads: false
intensedebate_comments: true

baseurl: # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://iRedScarf.github.io" # change this to the base hostname & protocol for your site

google_analytics:
# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
author: "A Red Scarf"
image: /iRedScarf.png
twitter:
  username: 
#  site:
facebook:
  #publisher: 
  #profile_id: 
  app_id: # cayman-blog
  #authors: 
#  admins:
